package com.mintic.videoclub.swings;

import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;

public class VistaPeliculas extends javax.swing.JFrame {

    public VistaPeliculas() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPMOpcionesPelicula = new javax.swing.JPopupMenu();
        jMIEditarPelicula = new javax.swing.JMenuItem();
        jMIAlquilarPelicula = new javax.swing.JMenuItem();
        jFrame1 = new javax.swing.JFrame();
        jSPTabla = new javax.swing.JScrollPane();
        jTInfoPeliculas = new javax.swing.JTable();
        jMBBarraPrincipial = new javax.swing.JMenuBar();
        jMArchivo = new javax.swing.JMenu();
        jMISalir = new javax.swing.JMenuItem();
        jMOperaciones = new javax.swing.JMenu();
        jMIAgregarPelicula = new javax.swing.JMenuItem();

        jPMOpcionesPelicula.setPreferredSize(new java.awt.Dimension(157, 94));

        jMIEditarPelicula.setText("Editar pelicula");
        jMIEditarPelicula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMIEditarPeliculaActionPerformed(evt);
            }
        });
        jPMOpcionesPelicula.add(jMIEditarPelicula);

        jMIAlquilarPelicula.setText("Transacciones");
        jMIAlquilarPelicula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMIAlquilarPeliculaActionPerformed(evt);
            }
        });
        jPMOpcionesPelicula.add(jMIAlquilarPelicula);

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Listado de peliculas");
        setBounds(new java.awt.Rectangle(150, 60, 500, 500));
        setName("listadoPeliculas"); // NOI18N
        setPreferredSize(new java.awt.Dimension(804, 604));
        setResizable(false);

        jTInfoPeliculas.setAutoCreateRowSorter(true);
        jTInfoPeliculas.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jTInfoPeliculas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "ID pelicula", "Nombre", "Duración (min)", "Descripción", "Año", "Categoria", "Estado"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, true, true, true, true, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTInfoPeliculas.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_NEXT_COLUMN);
        jTInfoPeliculas.setComponentPopupMenu(jPMOpcionesPelicula);
        jSPTabla.setViewportView(jTInfoPeliculas);

        jMArchivo.setText("Archivo");

        jMISalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/icons8-close-window-24.png"))); // NOI18N
        jMISalir.setText("Salir");
        jMISalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMISalirActionPerformed(evt);
            }
        });
        jMArchivo.add(jMISalir);

        jMBBarraPrincipial.add(jMArchivo);

        jMOperaciones.setText("Operaciones");

        jMIAgregarPelicula.setText("Agregar pelicula");
        jMIAgregarPelicula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMIAgregarPeliculaActionPerformed(evt);
            }
        });
        jMOperaciones.add(jMIAgregarPelicula);

        jMBBarraPrincipial.add(jMOperaciones);

        setJMenuBar(jMBBarraPrincipial);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jSPTabla, javax.swing.GroupLayout.DEFAULT_SIZE, 617, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jSPTabla, javax.swing.GroupLayout.DEFAULT_SIZE, 437, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMISalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMISalirActionPerformed
        this.dispatchEvent(new WindowEvent(this, WindowEvent.WINDOW_CLOSING));
        //System.exit(0);
    }//GEN-LAST:event_jMISalirActionPerformed

    private void jMIAgregarPeliculaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMIAgregarPeliculaActionPerformed
        NuevaPelicula nuevaPelicula = new NuevaPelicula(this, true);
        nuevaPelicula.addWindowListener(new WindowAdapter() {
            @Override
            public void windowClosed(WindowEvent e){
                // ejecutaré actualizar las peliculas
            }
        });
        nuevaPelicula.setVisible(true);
    }//GEN-LAST:event_jMIAgregarPeliculaActionPerformed

    private void jMIEditarPeliculaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMIEditarPeliculaActionPerformed
        EditarPelicula editarPelicula = new EditarPelicula(this, true);
        editarPelicula.addWindowListener(new WindowAdapter() {
            @Override
            public void windowClosed(WindowEvent e){
                // ejecutaré actualizar las peliculas
            }
        });
        editarPelicula.setVisible(true);
    }//GEN-LAST:event_jMIEditarPeliculaActionPerformed

    private void jMIAlquilarPeliculaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMIAlquilarPeliculaActionPerformed
        String estadoPelicula = "disponible";
        TransaccionesPelicula transaccionesPelicula = new TransaccionesPelicula(this, true);
        transaccionesPelicula.addWindowListener(new WindowAdapter() {
            @Override
            public void windowClosed(WindowEvent e){
                // ejecutaré actualizar las peliculas
            }
        });
        if (estadoPelicula.equals("disponible")) {
            transaccionesPelicula.setOperacion("alquiler");
        } else {
            transaccionesPelicula.setOperacion("devolucion");
        }
        transaccionesPelicula.setVisible(true);
    }//GEN-LAST:event_jMIAlquilarPeliculaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaPeliculas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaPeliculas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaPeliculas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaPeliculas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VistaPeliculas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFrame jFrame1;
    private javax.swing.JMenu jMArchivo;
    private javax.swing.JMenuBar jMBBarraPrincipial;
    private javax.swing.JMenuItem jMIAgregarPelicula;
    private javax.swing.JMenuItem jMIAlquilarPelicula;
    private javax.swing.JMenuItem jMIEditarPelicula;
    private javax.swing.JMenuItem jMISalir;
    private javax.swing.JMenu jMOperaciones;
    private javax.swing.JPopupMenu jPMOpcionesPelicula;
    private javax.swing.JScrollPane jSPTabla;
    private javax.swing.JTable jTInfoPeliculas;
    // End of variables declaration//GEN-END:variables
}
